#!/bin/bash
rm -rf /var/cache/* /tmp/*
mkdir -p /var/cache/apk/
find $1 \( -type d -name "doc" -o -type d -name "docs" \) -exec rm -rf {} \;
find $1 \( -type d -name ".gitignore" -o -type d -name ".git" \) -exec rm -rf {} \;
find $1 \( -type d -name ".gitattributes" -o -type d -name "*example*" \) -exec rm -rf {} \;
find $1 \( -type d -name "test" -o -type d -name "tests" \) -exec rm -rf {} \;

find $1 \( -name "*.txt" -o -name "*.ico" \) -exec rm -rf {} \;
find $1 \( -name "*.jpg" -o -name "*.jpeg" \) -exec rm -rf {} \;
find $1 \( -name "*.h" -o -name "*.cpp" \) -exec rm -rf {} \;
find $1 \( -name "*.c" -o -name "*README*" \) -exec rm -rf {} \;
find $1 \( -name "*example*" -o -name "*.sample" \) -exec rm -rf {} \;
find $1 \( -name "*.png" -o -name "*.gif" \) -exec rm -rf {} \;
find $1    -name "*.sh" -exec rm -rf {} \;
