#!/bin/bash
cp -r /bundle/* /home/developer/preinstalled/
if [ -f /bundle/.vimrc ]; then
  md5="$(md5sum '/bundle/.vimrc')"
  md5="${md5%% *}" # remove the first space and everything after it
  echo "source /home/developer/preinstalled/${md5}.vimrc" >> /home/developer/.vimrc
  cp '/bundle/.vimrc' /home/developer/preinstalled/${md5}\.vimrc
fi
echo "bundle added"
