#!/bin/bash
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
if [[ "${@}" == add-bundle* ]];
  then exec sh add-bundle
else
  if [ -f /.vimrc ]; then
    echo 'source /.vimrc' >> /home/developer/.vimrc
  fi
  eval vim $1
fi
